#!/usr/bin/env bash
set -euo pipefail

# export GHIDRA_FILES="/home/nicola/Desktop/Tesi/test/libmylib.so /home/nicola/Desktop/Tesi/test/file2.so"

if [ -z "${GHIDRA_FILES:-}" ]; then
  echo "Errore: GHIDRA_FILES non definita" >&2
  exit 1
fi

exec uvx pyghidra-mcp -t stdio $GHIDRA_FILES